# Generated by Django 6.0.1 on 2026-01-21 05:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رقم الشاسيه')),
                ('plate_number', models.CharField(db_index=True, max_length=32, verbose_name='رقم العربية / اللوحة')),
                ('important_detail', models.CharField(blank=True, max_length=255, verbose_name='تفاصيل مهمة')),
                ('current_km', models.PositiveIntegerField(default=0, verbose_name='العداد الحالي (KM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='garage.client')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('km_at_visit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM عند الزيارة')),
                ('worker_name', models.CharField(max_length=120, verbose_name='اسم العامل/الفني')),
                ('work_description', models.TextField(verbose_name='الشغل اللي اتعمل / الأعطال اللي اتصلحت')),
                ('parts_used', models.TextField(blank=True, verbose_name='قطع الغيار')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='garage.car')),
            ],
            options={
                'ordering': ['-visit_date', '-id'],
                'indexes': [models.Index(fields=['car', 'visit_date'], name='garage_visi_car_id_e78d7d_idx')],
            },
        ),
    ]
