# Generated by Django 5.1.1 on 2026-01-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='important_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='معلومة مهمة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=32, verbose_name='رقم اللوحة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رقم الهيكل (VIN)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='parts_used',
            field=models.TextField(blank=True, verbose_name='قطع الغيار المستخدمة'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='work_description',
            field=models.TextField(verbose_name='وصف العمل/التصليح'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='garage.worker', verbose_name='الفني'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
