# Generated by Django 5.2.3 on 2026-01-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_car_id_alter_car_important_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='رقم اللوحة'),
        ),
    ]
