# Generated by Django 5.2.3 on 2026-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_car_plate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='invoice_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='رقم الفاتورة'),
        ),
    ]
