# Generated by Django 5.2.3 on 2026-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_invoicecounter_visit_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('category', models.CharField(max_length=120, verbose_name='الفئة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
