# Generated by Django 5.2.3 on 2026-01-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المصروفات'),
        ),
    ]
