# Generated by Django 5.2.3 on 2026-01-26 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_visit_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة على العميل'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='اللي اتصرف على العربية'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='km_at_visit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='العداد عند الزيارة'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='work_description',
            field=models.TextField(verbose_name='وصف التصليح'),
        ),
    ]
