# Generated by Django 5.2.3 on 2026-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_visit_cost_alter_visit_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='اللي اتصرف على العربية من الورشة'),
        ),
    ]
