# Generated by Django 5.2.3 on 2026-01-31 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_alter_visit_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200, verbose_name='اسم القطعة')),
                ('client_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='على العميل')),
                ('workshop_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='على الورشة')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_parts', to='garage.visit')),
            ],
        ),
    ]
