# Generated by Django 5.2.3 on 2026-01-31 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_visitpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='expenses',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ كاش')),
                ('insta_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ على انستا باي')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='garage.visit')),
            ],
        ),
    ]
