# Generated by Django 5.2.3 on 2026-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_remove_visit_cost_remove_visit_expenses_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المصنعيه'),
        ),
    ]
