# Generated by Django 5.2.3 on 2026-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_remove_expense_created_at_expense_visit_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ كاش'),
        ),
    ]
